export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";
export const USER_SAVED_SUCCESS = "USER_SAVED_SUCCESS";

export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_SAVED_SUCCESS = "CATEGORY_SAVED_SUCCESS";
export const CATEGORY_FAILURE = "CATEGORY_FAILURE";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const PRODUCT_SAVED_SUCCESS = "PRODUCT_SAVED_SUCCESS";
export const PRODUCT_SAVED_REQUEST="PRODUCT_SAVED_REQUEST";
export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_FIND_REQUEST = "PRODUCT_FIND_REQUEST";
